models.py
from app import db
from datetime import datetime
import re

from flask_security import UserMixin, RoleMixin
 
	
def slugify(s):
	pattern = r'[^\w+]'
	return re.sub(pattern, '-', s)


roles_users = db.Table('roles_users',
	db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
	db.Column('role_id', db.Integer(), db.ForeignKey('role.id'))
	)

class User(db.Model, UserMixin):
	id = db.Column(db.Integer, primary_key=True)
	name = db.Column(db.String(140))
	password = db.Column(db.String(255))
	active = db.Column(db.Boolean())
	email = db.Column(db.String(100))
	roles = db.relationship('Role', secondary=roles_users, backref=db.backref('users', lazy='dynamic'))

	posts = db.relationship('Post', backref='user', lazy='dynamic')

	def __repr__(self):
		return '{}'.format(self.name)


class Role(db.Model, RoleMixin):
	id = db.Column(db.Integer(), primary_key=True)
	name = db.Column(db.String(100), unique=True)
	description = db.Column(db.String(255))

class Post(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	title = db.Column(db.String(140))
	subtitle = db.Column(db.String(140))
	slug = db.Column(db.String(140), unique=True)
	body = db.Column(db.Text)
	created = db.Column(db.DateTime, default=datetime.now())

	def __init__(self, *args, **kwargs):
		super(Post, self).__init__(*args, **kwargs)
		self.generate_slug()

	user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

	def generate_slug(self):
		if self.title:
			self.slug = slugify(self.title)

	def __repr__(self):
		return '<Post id: {}, title: {} >'.format(self.id, self.title)

app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy

from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

from flask_admin import Admin
from flask_admin import AdminIndexView
from flask_admin.contrib.sqla import ModelView


from flask_security import SQLAlchemyUserDatastore
from flask_security import Security, current_user

from flask import render_template
from flask import url_for, redirect, request

app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)


from models import *

class AdminMixin:
	def is_accessible(self):
		return current_user.has_role('admin')

	def inaccessible_callback(self, name, **kwargs):
		return redirect(url_for('security.login', next=request.url))


class BaseModelView(ModelView):
	def on_model_change(self, form, model, is_created):
		model.generate_slug()
		return super(BaseModelView, self). on_model_change(form, model, is_created)
		


class AdminView(AdminMixin, ModelView):
	pass
		
class HomeAdminView(AdminMixin, AdminIndexView):
	pass

class PostAdminView(AdminMixin, BaseModelView):
	form_columns = ['title', 'subtitle', 'body', 'user']


		

admin = Admin(app, 'FlaskApp', url='/', index_view=HomeAdminView(name='Home'))
admin.add_view(PostAdminView(Post, db.session))
admin.add_view(AdminView(User, db.session))



user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

main.py
from app import app
from app import db

import view

from posts.blueprint import posts

app.register_blueprint(posts, url_prefix='/blog')

if __name__ == '__main__':
	app.run()

posts/blueprint.py
from flask import Blueprint
from flask import render_template
from flask import request

from models import Post, User

from flask_security import login_required

posts = Blueprint('posts', __name__, template_folder='templates')

@posts.route('/')
def index():
	

	page = request.args.get('page')

	if page and page.isdigit():
		page = int(page)
	else:
		page = 1


	posts = Post.query.order_by(Post.created.desc())
	users = User.query.all()

	pages = posts.paginate(page=page, per_page=5)

	return render_template('posts/index.html', posts=posts, users=users, pages=pages)

@posts.route('/<slug>')
def post_detail(slug):
	post = Post.query.filter(Post.slug==slug).first_or_404()
	user = User.query.filter(User.id==post.user_id).first_or_404()
	return render_template('posts/post_detail.html', post=post, user=user)

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
  Posts
{% endblock %}

{% block page_title %}
My Blog
{% endblock %}

{% block subtitle %}
	My flask-blog
{% endblock %}

{% block admin %}



{% endblock %}

{% block content %}

  	{% for post in pages.items %}

<div class="post-preview">
                    <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">
                        <h2 class="post-title">
                            {{ post.title }}
                        </h2>
                        <h3 class="post-subtitle">
                            {{ post.subtitle }}
                        </h3>
                    </a>
                    <p class="post-meta">Posted by <a href="#">
                      {% for user in users %}
                          {% if user.id==post.user_id %}
                              {{ user.name }}
                          {% else %}
                          Unknown author
                          {% endif %}
                      {% endfor %}



                    </a> on {{post.created}}</p>
                </div>
                <hr>
  		
  	{% endfor %}


        <nav aria-label="Page navigation example">
                              <ul class="pagination">
                                <li class="page-item {% if not pages.has_prev %} disabled {% endif %}">
                                 
                                  <a class="page-link" href="./?page={{pages.prev_num}}">Previous</a>
                               
                                </li>
                                {% for page in pages.iter_pages() %}
                                <li class="page-item {% if page == pages.page %} active {% endif %}"><a class="page-link" href="./?page={{ page }}">{{ page }}</a></li>

                                {% endfor %}

                                <li class="page-item {% if not pages.has_next %} disabled {% endif %}">
                                  <a class="page-link" href="./?page={{pages.next_num}}">Next</a>
                                </li>
                              </ul>
        </nav>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
	{{ post.title }}
{% endblock %}

{% block page_title %}

{{ post.title }}

{% endblock %}

{% block subtitle %}
	<h2>{{ post.subtitle }}</h2>
	<span class="meta">Posted by <a href="#">{{ user.name }}</a> on {{ post.created }}</span>
{% endblock %}

{% block content %}
	 
	 {{ post.body }}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>
            {% block title %}



            {% endblock %} | Blog

    </title>

    <!-- Bootstrap Core CSS -->
    <link href="{{url_for('static', filename = 'vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">

    <!-- Theme CSS -->
    <!-- <link href="css/clean-blog.min.css" rel="stylesheet"> -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/clean-blog.min.css') }}">

    <!-- Custom Fonts -->
    <link href="{{url_for('static', filename = 'vendor/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <!-- <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/clean-blog.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/clean-blog.min.css') }}"> -->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{{ url_for('index') }}">Blog Flask </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.has_role('admin') %}

                    <li>
                        <a href="{{ url_for('admin.index') }}">admin</a>
                        
                    </li>
                    {% endif %}
                    <li>
                        <a href="{{url_for('index')}}">Home</a>
                    </li>
                    <li>
                        <a href="about.html">About</a>
                    </li>
                    <li>
                        <a href="contact.html">Contact</a>
                    </li>
                    {% if current_user.has_role('admin') %}
                    <li>
                        <a href="{{ url_for('security.logout') }}">Logout</a>
                        
                    </li>
                    {% else %}
                    <li>
                        <a href="{{ url_for('security.login') }}">Login</a>
                        
                    </li>


                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('{{url_for('static', filename = 'img/home-bg.jpg')}}'">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>{% block page_title %}

                            {% endblock %}
                        </h1>
                        <hr class="small">
                        <span class="subheading">
                            {% block subtitle %}

                            {% endblock %}
                        </span>
                        <span class="meta">{% block author %}     {% endblock %}</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                
              {% block content %}

              {% endblock %}
            
          
                <!-- Pager -->
           
            </div>
        </div>
    </div>

    <hr> 

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2016</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="js/jqBootstrapValidation.js"></script>
    <script src="js/contact_me.js"></script>

    <!-- Theme JavaScript -->
    <script src="js/clean-blog.min.js"></script>

</body>

</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}

	main page

{% endblock %}

{% block content_title %}
	main content

{% endblock %}

templates/security/login_user.html
{% extends 'base.html' %}


{% block title %}
	login
{% endblock %}

{% block page_title %}
    	You need to be loged in
{% endblock %}

{% block subtitle %}
	Really
{% endblock %}


{% block content %}

{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
<h1>{{ _('Login') }}</h1>
<form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
  {{ login_user_form.hidden_tag() }}
  {{ render_field_with_errors(login_user_form.email) }}
  {{ render_field_with_errors(login_user_form.password) }}
  {{ render_field_with_errors(login_user_form.remember) }}
  {{ render_field(login_user_form.next) }}
  {{ render_field(login_user_form.submit) }}
</form>
{% include "security/_menu.html" %}

{% endblock %}